# Generated by Django 2.0.6 on 2020-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='1.jpg', upload_to='image'),
        ),
    ]
