# Generated by Django 2.0.6 on 2020-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='image/1.jpg', upload_to='image/'),
        ),
    ]
